version: '3.3'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
    - .:/app
    - /app/node_modules
    ports:
    - 5000:5000
    - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .development.env
    environment:
      POSTGRES_ROOT_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DATABASE: POSTGRES_DB
      ports:
        POSTGRES_PORT:POSTGRES_PORT
      volumes:
        - db-config: /etc/postgres
        - db-data: /var/lib/postgres
        - ./db/backup/files/: /data_backup/data
